<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="AssemblyInfo.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../ErrorHandling/ErrorHandling.fsproj" />
        <ProjectReference Include="../Utils/Utils.fsproj" />
        <ProjectReference Include="../DoIt/DoIt.fsproj" />
        <ProjectReference Include="../Rohlik/Rohlik.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Console.fs" />

        <Compile Include="Command/Types.fs" />
        <Compile Include="Command/RepositoryBackup.fs" />
        <Compile Include="Command/RepositoryCreate.fs" />
        <Compile Include="Command/DirRemoveSubdirCommand.fs" />
        <Compile Include="Command/RepositoryBuildList.fs" />
        <Compile Include="Command/MigrateBuildCommand.fs" />
        <Compile Include="Command/Normalize.fs" />
        <Compile Include="Command/PhoneCodeStats.fs" />
        <Compile Include="Command/ContactStats.fs" />
        <Compile Include="Command/AzureFunc.fs" />
        <Compile Include="Command/DoitBackup.fs" />
        <Compile Include="Command/RohlikProducts.fs" />
        <Compile Include="Command/RohlikAnalyze.fs" />
        <Compile Include="Command/ParseGrafanaMetrics.fs" />
        <Compile Include="Command/StreamTestCommand.fs" />
        <Compile Include="Command/CognitoStats.fs" />
    </ItemGroup>

    <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
